In [1]:
from MiningMinima import *

Found rosetta database at: /usr/local/lib/python2.7/dist-packages/pyrosetta-2018.11+release.7c7790f-py2.7-linux-x86_64.egg/pyrosetta/database; using it....
PyRosetta-4 2017 [Rosetta PyRosetta4.Release.python27.ubuntu 2018.11+release.7c7790f7c7790fbb898f8210b54513b9f9c8a927c3e8d7f 2018-03-14T13:19:04] retrieved from: http://www.pyrosetta.org
(C) Copyright Rosetta Commons Member Institutions.
Created in JHU by Sergey Lyskov and PyRosetta Team.

core.init: Checking for fconfig files in pwd and ./rosetta/flags

core.init: Rosetta version: PyRosetta4.Release.python27.ubuntu r173 2018.11+release.7c7790f 7c7790fbb898f8210b54513b9f9c8a927c3e8d7f http://www.pyrosetta.org 2018-03-14T13:19:04
core.init: command: PyRosetta -ex1 -ex2aro -database /usr/local/lib/python2.7/dist-packages/pyrosetta-2018.11+release.7c7790f-py2.7-linux-x86_64.egg/pyrosetta/database
core.init: 'RNG device' seed mode, using '/dev/urandom', seed=454386426 seed_offset=0 real_seed=454386426
core.init.random: RandomGenerator:i

In [2]:
fuck = MiningMinima(seq1='cg', seq2='cg') 

core.chemical.GlobalResidueTypeSet: Finished initializing fa_standard residue type set.  Created 603 residue types
core.chemical.GlobalResidueTypeSet: Total time to initialize 0.703125 seconds.
core.scoring.etable: Starting energy table calculation
core.scoring.etable: smooth_etable: changing atr/rep split to bottom of energy well
core.scoring.etable: smooth_etable: spline smoothing lj etables (maxdis = 6)
core.scoring.etable: smooth_etable: spline smoothing solvation etables (max_dis = 6)
core.scoring.etable: Finished calculating energy tables.
basic.io.database: Database file opened: scoring/score_functions/hbonds/ref2015_params/HBPoly1D.csv
basic.io.database: Database file opened: scoring/score_functions/hbonds/ref2015_params/HBFadeIntervals.csv
basic.io.database: Database file opened: scoring/score_functions/hbonds/ref2015_params/HBEval.csv
basic.io.database: Database file opened: scoring/score_functions/hbonds/ref2015_params/DonStrength.csv
basic.io.database: Database file opened:

In [3]:
print np.linalg.norm(fuck.modes[1,:])

1.0000000000000007


In [4]:
print fuck.anharmonic_free_energy
print fuck.harmonic_free_energy

-14.531784123222753
-14.76031143915322


In [5]:
print fuck.modes[:,0]

[ 0.06421505  0.03759676 -0.03246734  0.24825857 -0.23668803 -0.34101587
  0.45363947 -0.44659345  0.5699035  -0.05321389 -0.08358397  0.08653995
  0.05601219  0.09483889]


In [6]:
ensemble = fuck.harmonic_ensemble()

In [ ]:
random_struct = np.zeros((fuck.n_dofs, 2000))

hmmm = np.random.randint(fuck.n_dofs, size = (fuck.n_dofs, 2000))

for j in range(2000):
    
    dphi = np.zeros_like(fuck.modes[:,0])
    
    for mode_idx in hmmm[:,j]:
    
        dphi += np.random.normal(0, 1/np.sqrt(fuck.eigenvalues[mode_idx]))*180./np.pi*fuck.modes[:,mode_idx]

    struct = [fuck.min_pose.torsion(fuck.dof_dict[key]) + dphi[key] for key in fuck.dof_dict]

    random_struct[:, j] = struct

In [12]:
print ensemble
pmm = PyMOLMover()
pmm.keep_history(True)
print ensemble[1,:]

[[218.65971637 -78.76762069 -56.73220904 ...  86.13660036  58.92622856
   76.99027105]
 [224.16865587 -79.31182198 -78.56099251 ...  71.22131151  57.9304836
   71.44280696]
 [214.3208875  -81.78740474 -45.88379834 ...  90.86548616  70.11693888
   73.2380441 ]
 ...
 [200.21587208 -55.07477232 -89.53537133 ...  75.4743342   82.79495529
   78.15449697]
 [207.84130798 -63.48993079 -88.95115156 ...  79.84696084  66.48475487
   76.72056068]
 [206.16457471 -66.75203927 -67.02572432 ...  84.2944021   77.79981259
   79.98637563]]
[ 224.16865587  -79.31182198  -78.56099251  165.22208417   69.47191092
 -145.10840913  -82.01941671  -56.88218691  174.54257465   46.9188516
   56.48007091   71.22131151   57.9304836    71.44280696]


In [18]:
pose = Pose()
pose.assign(fuck.min_pose)

for i in range(200):
    
    dofs = ensemble[i,:]
    for key in fuck.dof_dict: pose.set_torsion(fuck.dof_dict[key], dofs[key]) 
    pmm.apply(pose)
    print cu_ag.scorefxn(pose)
    print pose.jump(1)
    

-26.9308544292
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
-8.28686253184
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
13.0696225897
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
-16.1814746073
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
53.6386746673
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
-23.909736705
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
67.4208935246
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
144.518266639
RT -0.988666 0.149099 -0.01758 

-3.64843482446
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
-18.5814769289
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
-26.8346634688
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
-28.1289533618
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
-27.1588222346
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
-4.94609937593
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
1.90642738008
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
42.8876634133
RT -0.988666 0.149099 -0.017

RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
21.3906720331
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
81.6429694266
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
-8.83912865253
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
33.0985413248
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
-21.6330332478
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
52.2097219486
RT -0.988666 0.149099 -0.01758 0.149082 0.988822 0.002255 0.0177197 -0.000391421 -0.999843 6.23459 0.0885543 0.00692543  
230.605055609
RT -0.988666 0.149099 -0.01758 0.149082 0.9888

In [ ]:
print np.cov(ensemble)

In [ ]:
w,v = np.linalg.eigh(np.cov(ensemble.T))
print fuck.eigenvalues

In [ ]:
print 1/w*180./np.pi

In [ ]:

print fuck.min_energy - 0.5*fuck.n_dofs*np.log(2*np.pi) + 0.5*np.log(np.prod(1/w))

In [ ]:
print fuck.anharmonic_free_energy

In [ ]:
print fuck.min_pose

In [ ]:
mu = np.zeros(fuck.n_dofs)

In [ ]:
print mu

In [ ]:
mu = [fuck.min_pose.torsion(fuck.dof_dict[key]) for key in fuck.dof_dict]

In [ ]:
print mu
bitch = np.linalg.inv(fuck.hessian)

In [ ]:
shit = np.random.multivariate_normal(mu, bitch, size=(2000))

In [ ]:
print shit[0,:]

In [ ]:
random_struct = np.zeros((fuck.n_dofs, 2000))

for j in range(2000):
    
    random_struct[:,j] = np.random.multivariate_normal(mu, bitch)

In [ ]:
print random_struct

In [ ]:
print np.cov(random_struct)

In [ ]:
w,v = np.linalg.eigh(np.cov(random_struct))

In [ ]:
print 1/w


In [19]:
cu_ag = MiningMinima('cuc', 'gag')

{0: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff2956f8>, 1: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff295fb8>, 2: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff2955a8>, 3: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff295b58>, 4: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff295ab0>, 5: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff295b20>, 6: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff2957d8>, 7: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff295ed8>, 8: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff295500>, 9: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff295df8>, 10: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff295340>, 11: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff295e30>, 12: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff2957a0>, 13: <pyrosetta.rosetta.core.id.TorsionID object at 0x7facff295b90>, 14: <pyrosetta.rosetta.core.id.TorsionID object at 0x7fac

In [20]:
cu_ag.harmonic_free_energy

-30.00708342477897

In [21]:
ensemble = cu_ag.harmonic_ensemble()

In [22]:
cu_ag.eigenvalues

array([7.32461944e+00, 8.66581648e+00, 1.21571657e+01, 1.37491096e+01,
       1.43465161e+01, 1.44809899e+01, 1.62788294e+01, 2.52772044e+01,
       3.12543469e+01, 4.32693201e+01, 5.48805946e+01, 6.20355627e+01,
       1.12871705e+02, 1.26847411e+02, 1.78486871e+02, 1.88326091e+02,
       3.14338612e+02, 4.65634132e+02, 5.16544203e+02, 9.37992598e+02,
       1.38161422e+03, 1.81379965e+03, 2.40019376e+03, 6.71902810e+03,
       9.74060568e+03, 1.32472846e+04])

In [24]:
np.diag(1/cu_ag.eigenvalues)

array([[1.36525864e-01, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 1.15395936e-01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 8.22560148e-02

In [26]:
np.matmul( np.matmul( cu_ag.modes, np.diag(1/cu_ag.eigenvalues)), cu_ag.modes.T)

array([[ 2.12708684e-02, -1.64876466e-02,  1.01633429e-02,
        -1.11318898e-02, -5.36093718e-03,  1.69867745e-03,
        -1.20748274e-03, -1.86196750e-04,  8.69174345e-04,
        -6.98236682e-04,  8.49792777e-04,  1.94645299e-04,
        -6.12923912e-04,  1.29686729e-03, -6.29215896e-04,
         2.20595517e-03,  8.99810089e-04, -3.05400849e-03,
         2.51519331e-03, -1.34545836e-03, -9.85849363e-03,
        -3.12064682e-03, -1.43882113e-03, -1.12330003e-03,
        -6.47449118e-04, -2.16347957e-04],
       [-1.64876466e-02,  2.08038620e-02, -1.60560432e-02,
         1.88855568e-02,  2.35345108e-03, -3.09193940e-03,
         4.37955621e-04, -1.03231404e-03,  1.99175488e-03,
        -2.84697952e-04,  1.13510461e-04, -1.56993322e-04,
         2.49498447e-04, -2.09106839e-03,  1.39730450e-03,
         1.98295232e-03, -3.50161486e-03, -9.33678099e-04,
        -9.12254513e-04,  1.47338958e-03,  3.57666778e-03,
         2.08574155e-03,  1.20697850e-03,  8.17136144e-04,
         5.64

In [29]:
np.linalg.inv(cu_ag.hessian)

array([[ 2.12708684e-02, -1.64876466e-02,  1.01633429e-02,
        -1.11318898e-02, -5.36093718e-03,  1.69867745e-03,
        -1.20748274e-03, -1.86196750e-04,  8.69174345e-04,
        -6.98236682e-04,  8.49792777e-04,  1.94645299e-04,
        -6.12923912e-04,  1.29686729e-03, -6.29215896e-04,
         2.20595517e-03,  8.99810089e-04, -3.05400849e-03,
         2.51519331e-03, -1.34545836e-03, -9.85849363e-03,
        -3.12064682e-03, -1.43882113e-03, -1.12330003e-03,
        -6.47449118e-04, -2.16347957e-04],
       [-1.64876466e-02,  2.08038620e-02, -1.60560432e-02,
         1.88855568e-02,  2.35345108e-03, -3.09193940e-03,
         4.37955621e-04, -1.03231404e-03,  1.99175488e-03,
        -2.84697952e-04,  1.13510461e-04, -1.56993322e-04,
         2.49498447e-04, -2.09106839e-03,  1.39730450e-03,
         1.98295232e-03, -3.50161486e-03, -9.33678099e-04,
        -9.12254513e-04,  1.47338958e-03,  3.57666778e-03,
         2.08574155e-03,  1.20697850e-03,  8.17136144e-04,
         5.64